package com.example.myapplication.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.myapplication.GD.CuBean;

import com.example.myapplication.dao.CuBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cuBeanDaoConfig;

    private final CuBeanDao cuBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cuBeanDaoConfig = daoConfigMap.get(CuBeanDao.class).clone();
        cuBeanDaoConfig.initIdentityScope(type);

        cuBeanDao = new CuBeanDao(cuBeanDaoConfig, this);

        registerDao(CuBean.class, cuBeanDao);
    }
    
    public void clear() {
        cuBeanDaoConfig.clearIdentityScope();
    }

    public CuBeanDao getCuBeanDao() {
        return cuBeanDao;
    }

}
